apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  containers:
  - image: nginx
    name: test
    resources: {}
    volumeMounts:
    - mountPath: /data
      name: cache-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: cache-volume
    emptyDir: {}
status: {}
